# training
batch_size: 1
max_norm: 1
n_epochs: 1
seed: 42
learning: ['sl']  # sl - suvervised learning

learning_rate: 6.25e-5
warmup_steps: 1
adam_epsilon: 1.0e-8
weight_decay: 0.01
gamma: 1
gradient_accumulation_steps: 8
max_input_length: 403
max_num_examples: 80000 

# decoding
decoder: 'greedy'
top_k: 0
top_p: 1.0 # nucleus sampling #top_p: 0.9 # nucleus sampling
temperature: 1
max_length: 200
output_data: 'Test' #Train/Dev

# misc
fp16: '' # Set to O0, O1, O2 or O3 for fp16 training
logging: 100
re_tokenize: False
traintype: 'train'
rewardtype: ['ce']
device: 'cuda'
checkpoint: './checkpoint'
    
# dataset
dataset_type: ['amr'] # ['natural_questions', 'squad', 'drop', 'cardie']
input_format: 'original' #Optional for amr
dataset_path: 'DATA/'
dataset_cache: 'DATA/cache/amr'
small: False
use_silver_data: False
exclude_large: True
with_masking: False
split_sent: False
new_enc: False
